config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: :new
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: :destroy
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories, dependent: :destroy
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true
end

app/models/article_category.rb
# frozen_string_literal: true

class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
# frozen_string_literal: true

class Category < ActiveRecord::Base
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/models/user.rb
# frozen_string_literal: true

class User < ActiveRecord::Base
  has_many :articles, dependent: :delete_all
  validates :username, presence: true, uniqueness: { case_sensitive: false },
                       length: { minimum: 3, maximum: 25 }
  validates :email, presence: true, uniqueness: { case_sensitive: false },
                    format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password, presence: true
  has_secure_password
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    unless current_user.present?
      flash[:notice] = 'You must be logged in to perform that action!'
      redirect_to root_path
    end
  end

  def require_admin
    if !current_user.present? || !current_user&.admin?
      flash[:notice] = 'Only admin users can perform that action'
      redirect_to categories_path
    end
  end

  def require_same_user(object)
    if User.find(session[:user_id]) != object && !current_user.admin?
      flash[:notice] = 'You are not a valid user to perform that action'
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  before_action :set_article, only: %i[edit show destroy update]
  before_action :require_user, except: %i[index show]
  before_action only: %i[edit update destroy] do
    require_same_user(@article.user.id)
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = 'Article was successfully created'
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def show; end

  def edit; end

  def update
    if @article.update(article_params)
      flash[:notice] = 'Article was successfully updated'
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    flash[:notice] = 'Article was successfully deleted.'
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :require_admin, except: %i[index show]
  before_action :find_params, only: %i[show edit update]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(categories_params)
    if @category.save
      flash[:notice] = 'Category was succesfully created'
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def show
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  def edit; end

  def update
    if @category.update(category_params)
      flash[:notice] = 'Category name was succesfully updated'
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end

  private

  def categories_params
    params.require(:category).permit(:name)
  end

  def find_params
    @category = Category.find(params[:id])
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def home
    redirect_to articles_path if current_user.present?
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email])
    if user&.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = 'You have successfully logged in'
      redirect_to user_path(user)
    else
      flash.now[:notice] = 'There was something wrong with your login information'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'You have logged out'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[update edit show]
  before_action :require_admin, only: [:destroy]
  before_action only: %i[edit update destroy] do
    require_same_user(@user.id)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the MEKARSKI BLOG #{@user.username}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 3)
  end

  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 3)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = 'User and all his articles have been deleted'
    redirect_to users_path
  end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:notice] = 'User is successfully updated'
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def gravatar_for(user, size)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: 'img-circle')
  end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to article.title, article_path(article) %>
        </div>
        <div class="article-body">
          <%= truncate(article.description, length: 100) %><br>
          <small>Created by: <%= article.user.username if article.user %>,
            <%= time_ago_in_words(article.created_at) %> ago,
            last updated: <%= time_ago_in_words(article.updated_at) %> ago</small>
        </div>
        <% if article.categories.any? %>
          <p>Categories: <%= render article.categories %></p>
        <% end %>
        <% if current_user.present? && (current_user == article.user || current_user.admin?) %>
          <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %>
          <%= link_to "Delete this article", article_path(article), method: :delete,
                                              data: { confirm: "Are you sure You want to delete this article?"},
                                              class: "btn btn-xs btn-danger" %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>
<div class='row'>
  <div class='col-xs-12'>
    <%= form_for @article do |f| %>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :title %>
      </div>
      <div class="col-sm-10">
        <%= f.text_field :title, class: "form-control", placeholder: "Title for article", autofocus: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :description %>
      </div>
      <div class="col-sm-10">
        <%= f.text_area :description, class: "form-control", placeholder: "Description of article", autofocus: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-sm-offset-2 col-sm-8">
          <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
            <% cb.label(class: "checkbox-inline input") { cb.check_box(class: "checkbox") + cb.text} %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: "btn btn-default" %>
      </div>
    </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
    <%= link_to "Cancel request and return to article listing", articles_path %>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Edit an article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">List of all articles</h1>
<div align="center">
  <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>
<%= render 'article', obj: @articles %>
<div align="center">
  <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

app/views/articles/new.html.erb
<h1 align="center">Create an article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
  <ul class="listing">
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <li>Created by:</li>
        <li><%= link_to gravatar_for(@article.user, 160), user_path(@article.user) %></li>
        <li class="article-title">
          <%= link_to @article.user.username, user_path(@article.user) %>
        </li>
        <li><small>
          <%= pluralize(@article.user.articles.count, "article") if @article.user.articles %>
        </small></li>
      </div>
    </div>
  </ul>
  <h4 align="center"><strong>Description:</strong></h4>
  <hr>
  <%= @article.description %>
  <% if @article.categories.any? %>
    <p>Categories: <%= render @article.categories %></p>
  <% end %>
  <div class="article-actions">
    <% if current_user.present? && (current_user == @article.user || current_user.admin?) %>
      <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
      <%= link_to "Delete this article", article_path(@article), method: :delete,
                                          data: { confirm: "Are you sure You want to delete this article?"},
                                          class: "btn btn-xs btn-danger" %>
    <% end %>
    <%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>
  </div>
</div>

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>
<%= form_for @category do |f| %>
<div class="form-group">
  <div class="control-label col-sm-2">
    <%= f.label :name %>
  </div>
  <div class="col-sm-10">
    <%= f.text_field :name, class: "form-control", placeholder: "Category name", autofocus: true %>
  </div>
</div>
<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit class: "btn btn-default" %>
  </div>
</div>
<% end %>
<div class="col-xs-4 col-xs-offset-4">
  <%= link_to "Cancel request and return to article listing", articles_path %>
</div>

app/views/categories/edit.html.erb
<h1 align="center">Edit category</h1>
<%= render 'form' %>

app/views/categories/index.html.erb
<h1 align="center">Listing all Categories</h1>
<div align="center">
<%= will_paginate @categories, renderer: BootstrapPagination::Rails %>
<div align="center">
  <% @categories.each do |cat| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li class="article-title">
            <%= link_to "#{cat.name}", category_path(cat) %>
            <li><small><%= pluralize(cat.articles.count, "article") %></small>
          </li>
        </div>
      </div>
    </ul>
  <% end %>
</div>
<%= will_paginate @categories, renderer: BootstrapPagination::Rails %>
</div>

app/views/categories/new.html.erb
<h1 align="center">Create new category</h1>
<%= render 'form' %>

app/views/categories/show.html.erb
<h1 align="center"><%= "Category: " + @category.name %></h1>
<div align="center">
  <% if current_user.present? && current_user.admin? %>
    <span class="badge"><%= link_to "Edit category", edit_category_path(@category) %></span>
  <% end %>
  <%= will_paginate @category_articles, renderer: BootstrapPagination::Rails %>
</div>
<%= render 'articles/article', obj: @category_articles %>
<div align="center">
  <%= will_paginate @category_articles, renderer: BootstrapPagination::Rails %>
</div>

app/views/layouts/_footer.html.erb
<footer class="navbar navbar-fixed-bottom">
    Made by Kacper Mekarski
</footer>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class="alert alert-success" role="alert">
        <%= msg %>
      </div
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Mekarski Blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articles", articles_path %></li>
        <li><%= link_to "Users", users_path %></li>
        <% if current_user.present? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "New article", new_article_path %></li>
            </ul>
          </li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categeories<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "All categories", categories_path %></li>
              <% Category.all.each do |category| %>
                <li><%= link_to "#{category.name}", category_path(category) %></li>
              <% end %>
              <% if current_user.present? && current_user.admin? %>
                <li><%= link_to "Create new category", new_category_path %></li>
              <% end %>
            </ul>
          </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user.present? %>
          <li><%= link_to 'Log out', logout_path, method: :delete %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your profile <%= "Admin" if current_user.admin? %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Your profile", edit_user_path(current_user) %></li>
              <li><%= link_to "Show Your profile", user_path(current_user) %></li>
            </ul>
          </li>
          <% else %>
          <li><%= link_to 'Login', login_path %></li>
          <li><%= link_to 'Sign up', signup_path %></li>
          <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron pager">
  <div class="container">
    <h1>Welcome to my blog!</h1>
    <%= link_to "Sign up", signup_path, class: "btn btn-primary btn-large" %>
  </div>
</div>
<%= link_to "About", about_path %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h2 class="panel-title">
          <%= pluralize(obj.errors.count, "error") %>
          prevented the article from getting created
        </h2>
        <div class="panel-body">
        <ul>
          <% obj.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>
<div class='row'>
  <div class='col-xs-12'>
    <%= form_for @user do |f| %>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :username %>
      </div>
      <div class="col-sm-10">
        <%= f.text_field :username, class: "form-control", placeholder: "Username", autofocus: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :email %>
      </div>
      <div class="col-sm-10">
        <%= f.email_field :email, class: "form-control", placeholder: "Email", autofocus: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :password %>
      </div>
      <div class="col-sm-10">
        <%= f.password_field :password, class: "form-control", placeholder: "Enter password", autofocus: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-default") %>
      </div>
    </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
    <%= link_to "Cancel request and return to article listing", articles_path %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 align='center'>Edit your account</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1>Show all users</h1>
<div align="center">
  <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
  <% @users.each do |user| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li><%= link_to gravatar_for(user, 160), user_path(user) %></li>
          <li class="article-title">
            <%= link_to user.username, user_path(user) %>
          </li>
          <li><small><%= pluralize(user.articles.count, "article") if user.articles %></small></li>
          <% if current_user.present? && current_user.admin? %>
            <li><%= link_to "Delete this user", user_path(user), method: :delete,
            data: { confirm: "Are you sure you want to delete the user and all their articles?" } %></li>
          <% end %>
        </div>
      </div>
    </ul>
  <% end %>
  <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

app/views/users/new.html.erb
<h1 align="center">Signup for MEKARSKI BLOG</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Welcome <%= @user.username %></h1>
<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= gravatar_for @user, 150 %>
  </div>
</div>
<h4 align="center"><%= @user.username %>'s articles</h4>
<div align="center">
  <%= will_paginate @user_articles, renderer: BootstrapPagination::Rails %>
</div>
<%= render 'articles/article', obj: @user_articles %>
<div align="center">
  <%= will_paginate @user_articles, renderer: BootstrapPagination::Rails %>
</div>